### ISSUE TITLE
insert essay format questions into database

### ISSUE THREAD

**Issue by Reyhan-Sam** [RajveerSodhi/EduPool#118]
the essay format questions can be entered by the professor via text box as well as other file formats like doc/pdf/png/jpeg
similarly the questions can then be answered by students via text box submission as well as submitting other file formats like doc/pdf/png/jpeg. Make sure to manually test if we can read the uploaded files for the essay from the database accurately.

**Comment by RajveerSodhi** [comment]
Essay uploads and reading is enabled now.
