### ISSUE TITLE
Question feedback

### ISSUE THREAD

**Issue by Reyhan-Sam** [RajveerSodhi/EduPool#24]
As an instructor, I want to see if any questions were appealed by the students, that is if the students found anything wrong with any question. Acceptance Criteria: Instructor clicks on "Clarifications" and a list of all of the appealed questions pops up with the justifications given by the students.

**Comment by ameykarmarkar02** [comment]
The instructor should be able to remove a Question from appeal Questions once the issue has been addressed or if the Question was originally correct.

**Comment by ameykarmarkar02** [comment]
The instructor should be able to remove a Question from appeal Questions once the issue has been addressed or if the Question was originally correct
