### ISSUE TITLE
User Flow for enrolment functionality

### ISSUE THREAD

**Issue by SanjithSenthil** [RajveerSodhi/EduPool#73]
- Develop a streamlined user flow and intuitive design for enrolment functionality. These include achieving a 100% accuracy for the enrolment process.
- Functionalities include admin creating a course, student sending enrolment request for a course to admin, and admin accepting / decline the students request for enrolment in a particular course.

**Comment by Reyhan-Sam** [comment]
implemented enrollment functionality successfully

**Comment by SanjithSenthil** [comment]
- The user flow for enrolment functionality has been created.
- This user flow describing the interface as well as page navigation must now be followed while coding the application.
